### PR TITLE
FED-1354 Make actions run again

### PR DESCRIPTION
**Pull request by sydneyjodon-wk**
## Motivation
  

The GitHub actions that run the tests haven't been running on PRs. We should fix that

## Changes
  

- Fix indentation to get actions running again
- Update current Dart check to 2.18.7
- Make deploy step only run on master not pull requests since it can't be run on branches

## Review
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._

  

### QA Checklist
- [ ] Tests were updated and provide good coverage of the changeset and other affected code
- [ ] Manual testing was performed if needed
    - [ ] Steps from PR author:
        
      - [ ] CI passes
      - [ ] All GitHub actions are running
    - [ ] Anything falling under manual testing criteria [outlined in CONTRIBUTING.md][contributing-manual-testing]

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Frontend Frameworks Design member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/react_testing_library/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/react_testing_library/blob/master/CONTRIBUTING.md#manual-testing-criteria

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by hunterbreathat-wk** [comment]
These changes look good. Can we drop the stable job though? Since the org isn't ready for it, we won't pass until at least null safe and it will keep failing; it doesn't make sense to keep it.

**Comment by sydneyjodon-wk** [comment]
@hunterbreathat-wk I removed it at first, but then I noticed there's an entire pubspec.next.yaml for it that dependency overrides to the null safety branch of react-dart which made me think maybe it was intentionally there to test null safety or something - @greglittlefield-wf do you know what that was for?

**Comment by greglittlefield-wf** [comment]
@sydneyjodon-wk good question; I can't recall exactly what it was for. I can't seem to find anything in the commit history or initial PR https://github.com/Workiva/react_testing_library/pull/1. 

My guess is that it might have been a workaround to get things building in newer Dart SDKs, back at a time where there were bugs in the Dart SDK and build packages around null safety compilation (e.g., code would get opted in when it should've have, or wouldn't compile correctly with certain SDK/dependency sets). @aaronlademann-wf (looks like you added it initially), does that sound right?

Regardless, I feel like we should be able to remove all the `pubspec.next` stuff now though, especially now that we're building properly on newer SDKs, and are getting close to a true null safety release.

**Review by hunterbreathat-wk — APPROVED** [review]
QA +10

- Unused CI runs are no longer being used

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
